### ISSUE TITLE
It doesnt work

### ISSUE THREAD

**Issue by abrantie1z** [egbakou/RESTCountries.NET#1]
i installed the nuget into my .netstandard library, but when i call the api with an of the methods , i can get an error like no countries returned. am i missing something or the site is down?

**Comment by egbakou** [comment]
Are you sure?
All methods work perfectly !

**Comment by egbakou** [comment]
Or you are offline ?

**Comment by abrantie1z** [comment]
No, am connected through a LAN. do u install the nuget to platforms projects too?

**Comment by egbakou** [comment]
You have just to install the nuget package into your shared project.
You have also yo be connected to Internet.

**Comment by abrantie1z** [comment]
i can confirm is working now, it wasnt working previously.
