### ISSUE TITLE
IDD seems not correct

### ISSUE THREAD

**Issue by PassionateDeveloper86** [egbakou/RESTCountries.NET#13]
Hi,

thank you for your lib, I saw it on reddit and it fullfills a need I have very recently.

Sadly it seems the IDD is not well implemented.
Here you have a Root and a Suffix, weil Suxffix is a list.

E.g. for Germany your Root is +4 and your suffix is 9.
E.g. for Vatican Country you list the Root as +3 with 2 suffixes: 79 and 906698
E.g. for DomRep your root is +1 and 3 sufffices.

That seems "wrong":

Compared with https://countrycode.org

In Germany +49 is the complete country code. So the logic would be Take Root + Suffix.
In Vatican it seems +379 is the country code. So the logic would be take Root + 1 suffix (no way to find out which one, else then knowing)
In DomRep it seems +1 is the country code. So the logic would be ignore suffix, just take Root.

Can we have a logic in which the country code is a property allways or maybe have the IDD and Suffix all countries the same way?

**Comment by PassionateDeveloper86** [comment]
Any updates?

**Comment by egbakou** [comment]
Hi  @PassionateDeveloper86,
Thanks for the issue.

I will look at it this weekend.

**Comment by amatosg** [comment]
I'm working on this so the full IDD is also available :)

**Comment by mmattes** [comment]
Any news on this issue?

**Comment by amatosg** [comment]
I do  this on my free time, so it might take a while

**Comment by egbakou** [comment]
Fell free to reopen this issue if needed !
