### ISSUE TITLE
feature request add support to get states by country

### ISSUE THREAD

**Issue by donprecious** [egbakou/RESTCountries.NET#17]

**Comment by egbakou** [comment]
The dataset embedded in this project does not contain such information.

**Comment by donprecious** [comment]
you shouldn't have close this issue, because the embedded dataset does not contains such information , does not mean , it cannot be done. 
you should leave it open so someone in the community can pick it up, 
I even intend to pick it up, that why I raised an issue on contribution guidelines

**Comment by egbakou** [comment]
At first, I was hesitant to support these features for a variety of reasons. It is worth noting that countries can alter their states or administrative divisions for reasons ranging from political restructuring to population growth and territorial disputes.

However, after receiving numerous requests for this feature, I have added it to the backlog for consideration.
