### ISSUE TITLE
Support for other sources

### ISSUE THREAD

**Issue by wissevrowl** [egbakou/RESTCountries.NET#2]
Thank you for this package, it's very helpful in our project. One issue I've come across is the lack of updates on the source (restcountries.eu). Namely Great Britain still being listed as being in the EU. There's a fork running on restcountries.com that's more up to date. See https://gitlab.com/amatos/rest-countries

A thing to consider is to support changing source urls or straight out switching over to this other data source.

**Comment by egbakou** [comment]
Hi @wissevrowl 
Thank for your feedback. I will look at it soon ;)

**Comment by egbakou** [comment]
@wissevrowl issua resolved in the version 2.0.0
